static const char CONTENT_TERM_HTML[] PROGMEM = 
  "<html> <head> <title>EmonESP Terminal</title> <style> body {\n"
  "      color:#fff;\n"
  "      background-color:#300a24;\n"
  "    }\n"
  "    pre {\n"
  "      word-break: break-all;\n"
  "      white-space: pre-wrap;\n"
  "      margin-bottom: 0px;\n"
  "      font-family: monospace;\n"
  "      font-size: 13px;\n"
  "    }\n"
  "    input {\n"
  "      width: 100%;\n"
  "      font-family: monospace;\n"
  "      font-size: 13px;\n"
  "      border: none;\n"
  "      color: #fff;\n"
  "      background-color: #300a24;\n"
  "      padding: 0px;\n"
  "      margin-bottom: 13px;\n"
  "    }\n"
  "    input:focus {\n"
  "      outline: none;\n"
  "    } </style> <script src=\"lib.js\"></script> <script src=\"term.js\"></script> </head> <body> <pre id=\"term\"></pre> <form onsubmit=\"return term_input()\" action=\"#\"> <input id=\"input\"> </form> </body> </html> \n";
