# This file contains power quality values that are available for each phase
# Enabling these on every current channel is possible, but will produce a lot of data
# and sensors that are likely not needed.
# More details on each sensor here: https://esphome.io/components/sensor/atm90e32.html#configuration-variables

sensor:
- id: !extend ${addon5_id1}
  phase_a:
    reactive_power:
      name: ${ct31_name} VAR
      id: ct31VAR
    apparent_power:
      name: ${ct31_name} VA
      id: ct31VA
    harmonic_power:
      name: ${ct31_name} Harmonic
      id: ct31Har
    power_factor:
      name: ${ct31_name} Power Factor
      id: ct31PF
    phase_angle:
      name: ${ct31_name} Phase Angle
      id: ct31Angle
    peak_current:
      name: ${ct31_name} Peak A
      id: ct31Peak
  phase_b:
    reactive_power:
      name: ${ct32_name} VAR
      id: ct32VAR
    apparent_power:
      name: ${ct32_name} VA
      id: ct32VA
    harmonic_power:
      name: ${ct32_name} Harmonic
      id: ct32Har
    power_factor:
      name: ${ct32_name} Power Factor
      id: ct32PF
    phase_angle:
      name: ${ct32_name} Phase Angle
      id: ct32Angle
    peak_current:
      name: ${ct32_name} Peak A
      id: ct32Peak
  phase_c:
    reactive_power:
      name: ${ct33_name} VAR
      id: ct33VAR
    apparent_power:
      name: ${ct33_name} VA
      id: ct33VA
    harmonic_power:
      name: ${ct33_name} Harmonic
      id: ct33Har
    power_factor:
      name: ${ct33_name} Power Factor
      id: ct33PF
    phase_angle:
      name: ${ct33_name} Phase Angle
      id: ct33Angle
    peak_current:
      name: ${ct33_name} Peak A
      id: ct33Peak

- id: !extend ${addon5_id2}
  phase_a:
    reactive_power:
      name: ${ct34_name} VAR
      id: ct34VAR
    apparent_power:
      name: ${ct34_name} VA
      id: ct34VA
    harmonic_power:
      name: ${ct34_name} Harmonic
      id: ct34Har
    power_factor:
      name: ${ct34_name} Power Factor
      id: ct34PF
    phase_angle:
      name: ${ct34_name} Phase Angle
      id: ct34Angle
    peak_current:
      name: ${ct34_name} Peak A
      id: ct34Peak
  phase_b:
    reactive_power:
      name: ${ct35_name} VAR
      id: ct35VAR
    apparent_power:
      name: ${ct35_name} VA
      id: ct35VA
    harmonic_power:
      name: ${ct35_name} Harmonic
      id: ct35Har
    power_factor:
      name: ${ct35_name} Power Factor
      id: ct35PF
    phase_angle:
      name: ${ct35_name} Phase Angle
      id: ct35Angle
    peak_current:
      name: ${ct35_name} Peak A
      id: ct35Peak
  phase_c:
    reactive_power:
      name: ${ct36_name} VAR
      id: ct36VAR
    apparent_power:
      name: ${ct36_name} VA
      id: ct36VA
    harmonic_power:
      name: ${ct36_name} Harmonic
      id: ct36Har
    power_factor:
      name: ${ct36_name} Power Factor
      id: ct36PF
    phase_angle:
      name: ${ct36_name} Phase Angle
      id: ct36Angle
    peak_current:
      name: ${ct36_name} Peak A
      id: ct36Peak
