# This file contains power quality values that are available for each phase
# Enabling these on every current channel is possible, but will produce a lot of data
# and sensors that are likely not needed.
# More details on each sensor here: https://esphome.io/components/sensor/atm90e32.html#configuration-variables

sensor:
- id: !extend ${addon6_id1}
  phase_a:
    reactive_power:
      name: ${ct37_name} VAR
      id: ct37VAR
    apparent_power:
      name: ${ct37_name} VA
      id: ct37VA
    power_factor:
      name: ${ct37_name} Power Factor
      id: ct37PF
  phase_b:
    reactive_power:
      name: ${ct38_name} VAR
      id: ct38VAR
    apparent_power:
      name: ${ct38_name} VA
      id: ct38VA
    power_factor:
      name: ${ct38_name} Power Factor
      id: ct38PF
  phase_c:
    reactive_power:
      name: ${ct39_name} VAR
      id: ct39VAR
    apparent_power:
      name: ${ct39_name} VA
      id: ct39VA
    power_factor:
      name: ${ct39_name} Power Factor
      id: ct39PF

- id: !extend ${addon6_id2}
  phase_a:
    reactive_power:
      name: ${ct40_name} VAR
      id: ct40VAR
    apparent_power:
      name: ${ct40_name} VA
      id: ct40VA
    power_factor:
      name: ${ct40_name} Power Factor
      id: ct40PF
  phase_b:
    reactive_power:
      name: ${ct41_name} VAR
      id: ct41VAR
    apparent_power:
      name: ${ct41_name} VA
      id: ct41VA
    power_factor:
      name: ${ct41_name} Power Factor
      id: ct41PF
  phase_c:
    reactive_power:
      name: ${ct42_name} VAR
      id: ct42VAR
    apparent_power:
      name: ${ct42_name} VA
      id: ct42VA
    power_factor:
      name: ${ct42_name} Power Factor
      id: ct42PF
