# This file contains power quality values that are available for each phase
# Enabling these on every current channel is possible, but will produce a lot of data
# and sensors that are likely not needed.
# More details on each sensor here: https://esphome.io/components/sensor/atm90e32.html#configuration-variables

sensor:
- id: !extend ${addon5_id1}
  phase_a:
    reactive_power:
      name: ${ct31_name} VAR
      id: ct31VAR
    apparent_power:
      name: ${ct31_name} VA
      id: ct31VA
    power_factor:
      name: ${ct31_name} Power Factor
      id: ct31PF
  phase_b:
    reactive_power:
      name: ${ct32_name} VAR
      id: ct32VAR
    apparent_power:
      name: ${ct32_name} VA
      id: ct32VA
    power_factor:
      name: ${ct32_name} Power Factor
      id: ct32PF
  phase_c:
    reactive_power:
      name: ${ct33_name} VAR
      id: ct33VAR
    apparent_power:
      name: ${ct33_name} VA
      id: ct33VA
    power_factor:
      name: ${ct33_name} Power Factor
      id: ct33PF

- id: !extend ${addon5_id2}
  phase_a:
    reactive_power:
      name: ${ct34_name} VAR
      id: ct34VAR
    apparent_power:
      name: ${ct34_name} VA
      id: ct34VA
    power_factor:
      name: ${ct34_name} Power Factor
      id: ct34PF
  phase_b:
    reactive_power:
      name: ${ct35_name} VAR
      id: ct35VAR
    apparent_power:
      name: ${ct35_name} VA
      id: ct35VA
    power_factor:
      name: ${ct35_name} Power Factor
      id: ct35PF
  phase_c:
    reactive_power:
      name: ${ct36_name} VAR
      id: ct36VAR
    apparent_power:
      name: ${ct36_name} VA
      id: ct36VA
    power_factor:
      name: ${ct36_name} Power Factor
      id: ct36PF
