# Offset calibration values fine tuned via the output of the semi-automatic calibrations
# Values should be copied in from the meter's ESPHome log
# See details on semi-automatic calibrations here: 
# https://esphome.io/components/sensor/atm90e32.html#calibration

sensor:
  id: !extend ${addon1_id1}
  phase_a:
    offset_voltage: 0
    offset_current: 0
    offset_active_power: 0
    offset_reactive_power: 0
  phase_b:
    offset_voltage: 0
    offset_current: 0
    offset_active_power: 0
    offset_reactive_power: 0
  phase_c:
    offset_voltage: 0
    offset_current: 0
    offset_active_power: 0
    offset_reactive_power: 0

  id: !extend ${addon1_id1}
  phase_a:
    offset_voltage: 0
    offset_current: 0
    offset_active_power: 0
    offset_reactive_power: 0
  phase_b:
    offset_voltage: 0
    offset_current: 0
    offset_active_power: 0
    offset_reactive_power: 0
  phase_c:
    offset_voltage: 0
    offset_current: 0
    offset_active_power: 0
    offset_reactive_power: 0
