# Details: https://esphome.io/components/sensor/atm90e32.html#calibration
# Main Board Semi-automatic Calibration Buttons
###############################################
button:
  - platform: atm90e32
    id: ${main_meter_id1}
    run_offset_calibration:
      name: "1. Run ${main_meter_name1} Offset Cal"
    clear_offset_calibration:
      name: "z1. Clear ${main_meter_name1} Offset Cal"
    run_power_offset_calibration:
      name: "2. Run ${main_meter_name1} Power Offset Cal"
    clear_power_offset_calibration:
      name: "z2. Clear ${main_meter_name1} Power Offset Cal"
    run_gain_calibration:
      name: "3. Run ${main_meter_name1} Gain Cal"
    clear_gain_calibration:
      name: "z3. Clear ${main_meter_name1} Gain Cal"

  - platform: atm90e32
    id: ${main_meter_id2}
    run_offset_calibration:
      name: "1. Run ${main_meter_name2} Offset Cal"
    clear_offset_calibration:
      name: "z1. Clear ${main_meter_name2} Offset Cal"
    run_power_offset_calibration:
      name: "2. Run ${main_meter_name2} Power Offset Cal"
    clear_power_offset_calibration:
      name: "z2. Clear ${main_meter_name2} Power Offset Cal"
    run_gain_calibration:
      name: "3. Run ${main_meter_name2} Gain Cal"
    clear_gain_calibration:
      name: "z3. Clear ${main_meter_name2} Gain Cal"

# Main Board V & I Calibration Reference Fields
###############################################
# Use these to input a known value being measured by a CT or voltage transformer
number:
  - platform: atm90e32
    id: ${main_meter_id1}
    reference_voltage:
      # will copy to phase_b/c for calibration reference
      phase_a:
        name: "${main_meter_name1} Ref V 1"
    reference_current:
      phase_a:
        name: "${ct1_name} Ref Current"
      phase_b:
        name: "${ct2_name} Ref Current"
      phase_c:
        name: "${ct3_name} Ref Current"

  - platform: atm90e32
    id: ${main_meter_id2}
    reference_voltage:
      # needed to calibrate voltage registers even if not output
      phase_a:
        name: "${main_meter_name2} Ref V 2" 
    reference_current:
      phase_a:
        name: "${ct4_name} Ref Current"
      phase_b:
        name: "${ct5_name} Ref Current"
      phase_c:
        name: "${ct6_name} Ref Current"
