# These fields display the status of each CT, or phase, with a short text description
# See more details here: https://esphome.io/components/sensor/atm90e32.html#text-sensor

# Status Fields
###############
text_sensor:
  - platform: atm90e32
    id: ${addon6_id1}
    phase_status:
      phase_a:
        name: "${ct37_name} Status"
      phase_b:
        name: "${ct38_name} Status"
      phase_c:
        name: "${ct39_name} Status"

  - platform: atm90e32
    id: ${addon6_id2}
    phase_status:
      phase_a:
        name: "${ct40_name} Status"
      phase_b:
        name: "${ct41_name} Status"
      phase_c:
        name: "${ct42_name} Status"
