# These fields display the status of each CT, or phase, with a short text description
# See more details here: https://esphome.io/components/sensor/atm90e32.html#text-sensor

# Status Fields
###############
text_sensor:
  - platform: atm90e32
    id: ${addon3_id1}
    phase_status:
      phase_a:
        name: "${ct19_name} Status"
      phase_b:
        name: "${ct20_name} Status"
      phase_c:
        name: "${ct21_name} Status"

  - platform: atm90e32
    id: ${addon3_id2}
    phase_status:
      phase_a:
        name: "${ct22_name} Status"
      phase_b:
        name: "${ct23_name} Status"
      phase_c:
        name: "${ct24_name} Status"
