#
# Project Configuration File
#
# A detailed documentation with the EXAMPLES is located here:
# http://docs.platformio.org/en/latest/projectconf.html
#

# A sign `#` at the beginning of the line indicates a comment
# Comment lines are ignored.

# Simple and base environment
# [env:mybaseenv]
# platform = %INSTALLED_PLATFORM_NAME_HERE%
# framework =
# board =
#
# Automatic targets - enable auto-uploading
# targets = upload

[platformio]
default_envs = emonesp-nodemcu32s
data_dir = src/data

[common]
version = -DBUILD_TAG=3.0
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
framework = arduino
lib_deps =
        knolleary/PubSubClient@2.8
        esp32async/ESPAsyncWebServer@3.10.1
        esp32async/AsyncTCP@3.4.10
        https://github.com/CircuitSetup/ATM90E32.git#c4b4c284dfc895df9b4000d5a1519c537a8c0b57
monitor_speed = 115200
board_build.filesystem = littlefs

[env:emonesp-nodemcu32s]
board = nodemcu-32s
platform = ${common.platform}
framework = ${common.framework}
lib_deps = ${common.lib_deps}
build_flags =
  ${common.version}
  -DCS_BOARD_PROFILE=CS_BOARD_PROFILE_NODEMCU32S
  #-DWIFI_LED=LED_BUILTIN
  #-DENABLE_DEBUG
  #-DCORE_DEBUG_LEVEL=5
  #-DTHREE_PHASE
build_src_flags =
	-DDEBUG_PORT=Serial
	-ggdb
monitor_speed = ${common.monitor_speed}
board_build.filesystem = ${common.board_build.filesystem}
board_build.flash_mode = qio
board_build.f_cpu = 80000000L
upload_port = COM4
upload_speed = 921600
upload_resetmethod = nodemcu

[env:emonesp-nodemcu32s-littlefs]
board = nodemcu-32s
platform = ${common.platform}
framework = ${common.framework}
board_build.filesystem = ${common.board_build.filesystem}
upload_port = COM4
upload_speed = 921600
upload_resetmethod = nodemcu
targets = buildfs, uploadfs

[env:emonesp_littlefs]
extends = env:emonesp-nodemcu32s-littlefs

[env:emonesp-lilygo-t-eth-lite-s3]
board = esp32-s3-devkitc1-n16r8
platform = ${common.platform}
framework = ${common.framework}
lib_deps = ${common.lib_deps}
build_flags =
  ${common.version}
  -DCS_BOARD_PROFILE=CS_BOARD_PROFILE_LILYGO_T_ETH_LITE_S3
  -DENABLE_DEBUG
  -DCORE_DEBUG_LEVEL=5
build_src_flags =
	-DDEBUG_PORT=Serial
	-ggdb
monitor_speed = ${common.monitor_speed}
board_build.filesystem = ${common.board_build.filesystem}
board_build.flash_mode = dio
board_build.f_cpu = 240000000L

[env:emonesp-lilygo-t-eth-lite-s3-littlefs]
board = esp32-s3-devkitc1-n16r8
platform = ${common.platform}
framework = ${common.framework}
board_build.filesystem = ${common.board_build.filesystem}
board_build.flash_mode = dio
targets = buildfs, uploadfs

[env:emonesp-waveshare-esp32-s3-eth]
board = esp32-s3-devkitc1-n16r8
platform = ${common.platform}
framework = ${common.framework}
lib_deps = ${common.lib_deps}
build_flags =
  ${common.version}
  -DCS_BOARD_PROFILE=CS_BOARD_PROFILE_WAVESHARE_ESP32_S3_ETH
  -DENABLE_DEBUG
  -DCORE_DEBUG_LEVEL=5
build_src_flags =
	-DDEBUG_PORT=Serial
	-ggdb
monitor_speed = ${common.monitor_speed}
board_build.filesystem = ${common.board_build.filesystem}
board_build.flash_mode = dio
board_build.f_cpu = 240000000L

[env:emonesp-waveshare-esp32-s3-eth-littlefs]
board = esp32-s3-devkitc1-n16r8
platform = ${common.platform}
framework = ${common.framework}
board_build.filesystem = ${common.board_build.filesystem}
board_build.flash_mode = dio
targets = buildfs, uploadfs

[env:emonesp_deploy]
extends = env:emonesp-nodemcu32s
