{
 "title": "CircuitSetup 6 Channel Energy Meter - 1 add-on board",
 "tags": [ "Energy Meter" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cost", "label": "Cost/kWh", "query": "0.2" }
  ]
 },
 "panels": [
  {
   "title": "Total Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "SELECT mean(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = '6c_total_kwh') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600/1000*$cost" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_total_watts" }
     ]
    }
   ]
  },
  {
   "title": "Total kWh",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_total_watts" }
     ]
    }
   ]
  },
  {
   "title": "Volts & Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Volts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "V",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_volts_a" }
     ]
    },
    {
     "alias": "Hz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "hz",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_freq_a" }
     ]
    }
   ]
  },
  {
   "title": "Cost per Circuit",
   "type": "graph",
   "description": "Based on cost per kWh",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "CT1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600/1000*$cost" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct1_watts" }
     ]
    },
    {
     "alias": "CT2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600/1000*$cost" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct2_watts" }
     ]
    },
    {
     "alias": "CT3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600/1000*$cost" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct3_watts" }
     ]
    },
    {
     "alias": "CT4",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600/1000*$cost" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct4_watts" }
     ]
    },
    {
     "alias": "CT5",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600/1000*$cost" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct5_watts" }
     ]
    },
    {
     "alias": "CT6",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600/1000*$cost" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct6_watts" }
     ]
    },
    {
     "alias": "CT7",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600/1000*$cost" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct7_watts" }
     ]
    },
    {
     "alias": "CT8",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600/1000*$cost" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct8_watts" }
     ]
    },
    {
     "alias": "CT9",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600/1000*$cost" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct9_watts" }
     ]
    },
    {
     "alias": "CT10",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600/1000*$cost" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct10_watts" }
     ]
    },
    {
     "alias": "CT11",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600/1000*$cost" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct11_watts" }
     ]
    },
    {
     "alias": "CT12",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " / 3600/1000*$cost" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct12_watts" }
     ]
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_total_watts" }
     ]
    },
    {
     "alias": "Amps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "A",
     "query": "SELECT mean(\"value\") FROM \"A\" WHERE (\"entity_id\" = '6c_ct1_amps') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_total_amps" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "description": "Power from all CTs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "alias": "CT1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct1_watts" }
     ]
    },
    {
     "alias": "CT2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct2_watts" }
     ]
    },
    {
     "alias": "CT3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct3_watts" }
     ]
    },
    {
     "alias": "CT4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct4_watts" }
     ]
    },
    {
     "alias": "CT5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct5_watts" }
     ]
    },
    {
     "alias": "CT6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct6_watts" }
     ]
    },
    {
     "alias": "CT7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct7_watts" }
     ]
    },
    {
     "alias": "CT8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct8_watts" }
     ]
    },
    {
     "alias": "CT9",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct9_watts" }
     ]
    },
    {
     "alias": "CT10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "SELECT mean(\"value\") FROM \"W\" WHERE (\"entity_id\" = '6c_ct10_watts') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct10_watts" }
     ]
    },
    {
     "alias": "CT11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "SELECT mean(\"value\") FROM \"W\" WHERE (\"entity_id\" = '6c_ct10_watts') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct11_watts" }
     ]
    },
    {
     "alias": "CT12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "SELECT mean(\"value\") FROM \"W\" WHERE (\"entity_id\" = '6c_ct10_watts') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "6c_ct12_watts" }
     ]
    }
   ]
  }
 ]
}